"""results/*.json -> LaTeX macros: the paper never contains a typed number.

A value with a sibling `<key>_sigma` is rounded to the decimal place of that
sigma's second significant digit, and the sigma with it; any other float keeps
three significant digits; integers are verbatim; NaN renders as a dash, magnitudes below 1e-3 go
through siunitx `\\num`, negatives are wrapped in `\\ensuremath`; infinities raise.
"""

import json
import math
import re
from pathlib import Path

_DIGITS = "Zero One Two Three Four Five Six Seven Eight Nine".split()


def macro_name(stem: str, key: str) -> str:
    parts = re.split(r"[_\-.]", f"{stem}_{key}")
    name = "".join(p[:1].upper() + p[1:] for p in parts if p)
    return re.sub(r"\d", lambda m: _DIGITS[int(m.group())], name)


def _decimals(sigma: float) -> int:
    return max(0, 1 - int(math.floor(math.log10(abs(sigma)))))


def _plain(value: float, sigma: float | None) -> str:
    if sigma is not None and math.isfinite(sigma) and sigma > 0:
        return f"{value:.{_decimals(sigma)}f}"
    if abs(value) >= 100:
        return f"{value:.0f}"
    if value != 0 and abs(value) < 1e-3:
        return f"\\num{{{value:.3g}}}"
    return f"{value:.3g}"


def format_value(value: float | int, sigma: float | None = None) -> str:
    if isinstance(value, int):
        return str(value)
    if math.isnan(value):
        return "--"
    text = _plain(value, sigma)
    return f"\\ensuremath{{{text}}}" if text.startswith("-") else text


def flatten(results_dir: Path) -> dict[str, str]:
    macros: dict[str, str] = {}
    origin: dict[str, str] = {}
    for path in sorted(Path(results_dir).glob("*.json")):
        doc = json.loads(path.read_text())
        scalars = {
            k: v for k, v in doc.items() if isinstance(v, int | float) and not isinstance(v, bool)
        }
        for key, value in scalars.items():
            if isinstance(value, float) and math.isinf(value):
                raise ValueError(f"non-finite value in {path.name}:{key}")
            if key.endswith("_sigma") and key[: -len("_sigma")] in scalars:
                base = scalars[key[: -len("_sigma")]]
                text = (
                    format_value(value, value) if isinstance(base, float) else format_value(value)
                )
            else:
                text = format_value(value, scalars.get(f"{key}_sigma"))
            name = macro_name(path.stem, key)
            if name in macros:
                raise ValueError(
                    f"macro \\{name} from {path.name}:{key} collides with {origin[name]}"
                )
            macros[name] = text
            origin[name] = f"{path.name}:{key}"
    return macros


def write_numbers(results_dir: Path, out_path: Path) -> Path:
    lines = ["% Generated by `cafetomo numbers` from results/*.json. Do not edit."]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(flatten(results_dir).items())]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    return out_path
